// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Path from "jsr:@std/path";
import * as Toml from "jsr:@std/toml";
import * as Yaml from "jsr:@std/yaml";
import * as Caml_exceptions from "rescript/lib/es6/caml_exceptions.js";
import * as Deno$TsirysndrRescriptDeno from "../src/Deno.res.js";
import * as Globals$TsirysndrRescriptDeno from "../src/Globals.res.js";
import * as BufferTs from "https://deno.land/std@0.212.0/io/buffer.ts";
import * as ModTs from "https://deno.land/std@0.212.0/assert/mod.ts";
import * as TarTs from "https://deno.land/std@0.212.0/archive/tar.ts";
import * as UntarTs from "https://deno.land/std@0.212.0/archive/untar.ts";

var obj = {
  a: 10,
  b: "hello"
};

console.log(Deno.inspect(obj, undefined));

console.log(Path.join("hello", "world"));

console.log("Hello, world!");

console.log(Deno.env.get("HOME"));

console.log(Deno.env.has("PATH"));

var yaml = "\n  id: 1\n  name: \"Alice\"\n";

console.log(Yaml.parse(yaml, undefined));

var tar = new TarTs.Tar();

var content = new TextEncoder().encode("hello");

var b = new BufferTs.Buffer(content);

var obj$1 = {
  title: "TOML example",
  owner: {
    name: "Bob",
    bio: "Bob is a cool guy"
  }
};

console.log(Toml.stringify(obj$1, undefined));

console.log(b.empty());

console.log(b.bytes());

tar.append("hello.txt", {
      reader: b,
      contentSize: b.bytes().length
    });

console.log(tar);

console.log(tar.getReader());

var reader = tar.getReader();

var untar = new UntarTs.Untar(reader);

console.log(await untar.extract());

ModTs.assert(true);

ModTs.assertAlmostEquals(0.01, 0.02, 0.1, undefined);

ModTs.assertArrayIncludes([
      1,
      2,
      3
    ], [
      1,
      2
    ], undefined);

ModTs.assertEquals(1, 1, undefined, undefined);

ModTs.assertExists(1, undefined);

ModTs.assertFalse(false, undefined);

ModTs.assertGreater(4, 1, undefined);

ModTs.assertGreaterOrEqual(4, 4, undefined);

ModTs.assertLess(1, 4, undefined);

ModTs.assertLessOrEqual(4, 4, undefined);

ModTs.assertMatch("hello", /hello/, undefined);

ModTs.assertNotEquals(1, 2, undefined);

ModTs.assertNotMatch("hello", /world/, undefined);

ModTs.assertNotStrictEquals(1, 2, undefined);

ModTs.assertObjectMatch({
      a: 1
    }, {
      a: 1
    }, undefined);

var z = {
  a: 1
};

ModTs.assertStrictEquals(z, z, undefined);

ModTs.assertStringIncludes("hello", "ello", undefined);

var MyException = /* @__PURE__ */Caml_exceptions.create("Demo-TsirysndrRescriptDeno.MyException");

ModTs.assertThrows((function () {
        throw {
              RE_EXN_ID: MyException,
              message: "hello",
              Error: new Error()
            };
      }), undefined);

console.log(ModTs.equal({
          a: 1
        }, {
          a: 1
        }));

var c = new AbortController();

console.log(c.signal);

console.log(new URL("https://deno.land").toString());

var pattern = Globals$TsirysndrRescriptDeno.$$URLPattern.$$new({
      TAG: "String",
      _0: "https://deno.land"
    }, undefined);

console.log(pattern);

var pattern$1 = Globals$TsirysndrRescriptDeno.$$URLPattern.$$new({
      TAG: "URLPatternInit",
      _0: {
        pathname: "/x",
        baseURL: "https://deno.land"
      }
    }, undefined);

console.log(pattern$1);

var params = new URLSearchParams({
      foo: "bar"
    });

console.log(params.toString());

console.log(btoa("hello"));

console.log(atob("aGVsbG8gd29ybGQ="));

var data = new FormData();

Globals$TsirysndrRescriptDeno.$$FormData.append(data, "foo", {
      TAG: "String",
      _0: "bar"
    }, undefined);

console.log(Deno.networkInterfaces());

var request = Globals$TsirysndrRescriptDeno.$$Request.$$new({
      TAG: "String",
      _0: "http://localhost:9007"
    }, {
      body: {
        TAG: "FormData",
        _0: data
      },
      method: "POST"
    });

console.log(request);

console.log(await request.formData());

var text = new TextEncoder().encode("hello");

console.log(Globals$TsirysndrRescriptDeno.$$TextDecoder.$$new(undefined, undefined).decode(text, undefined));

console.log(await Deno.resolveDns("deno.land", "A", undefined));

var command = new (Deno.Command)("ls", {
      stdout: "piped",
      stderr: "piped"
    });

var $$process = command.spawn();

var output = await $$process.output();

var status = await $$process.status;

console.log(status.code);

var decoder = Globals$TsirysndrRescriptDeno.$$TextDecoder.$$new(undefined, undefined);

console.log(decoder.decode(output.stdout, undefined));

Deno$TsirysndrRescriptDeno.serveWithOptions({
      port: 9007
    }, undefined, (async function (req) {
        var headers = req.headers;
        var body = await req.text();
        console.log(headers);
        console.log(headers.get("User-Agent"));
        console.log(body);
        return Globals$TsirysndrRescriptDeno.$$Response.$$new({
                    TAG: "String",
                    _0: "Hello, world!"
                  }, undefined);
      }));

var a = 1;

var y = z;

export {
  yaml ,
  tar ,
  content ,
  b ,
  obj$1 as obj,
  reader ,
  untar ,
  a ,
  z ,
  y ,
  MyException ,
  c ,
  pattern$1 as pattern,
  params ,
  data ,
  request ,
  text ,
  command ,
  $$process ,
  output ,
  status ,
  decoder ,
}
/*  Not a pure module */
