// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Assert from "jsr:@std/assert";
import * as Deno$TsirysndrRescriptDeno from "../src/Deno.res.js";

Deno$TsirysndrRescriptDeno.test({
      name: "example test",
      fn: {
        TAG: "Fn",
        _0: (function () {
            Assert.assertEquals("world", "world", undefined, undefined);
          })
      }
    });

export {
  
}
/*  Not a pure module */
