// Generated by ReScript, PLEASE EDIT WITH CARE


var Tar = {};

var TarMetaWithLinkName = {};

var TarHeader = {};

var TarEntry = {};

var Untar = {
  TarMetaWithLinkName: TarMetaWithLinkName,
  TarHeader: TarHeader,
  TarEntry: TarEntry
};

export {
  Tar ,
  Untar ,
}
/* No side effect */
