// Generated by ReScript, PLEASE EDIT WITH CARE


var TDoubleDash = {};

var TAliases = {};

var TBooleans = {};

var TStrings = {};

var TCollectable = {};

var TNegatable = {};

var TDefault = {};

var ParseOptions = {};

var Args = {};

var PromptSecretOptions = {};

var Nullable = {};

export {
  TDoubleDash ,
  TAliases ,
  TBooleans ,
  TStrings ,
  TCollectable ,
  TNegatable ,
  TDefault ,
  ParseOptions ,
  Args ,
  PromptSecretOptions ,
  Nullable ,
}
/* No side effect */
