// Generated by ReScript, PLEASE EDIT WITH CARE


var TarStreamFile = {};

var TarStreamOptions = {};

var TarStreamDir = {};

var TarStreamInput = {};

var TarStream = {};

var OldStyleFormat = {};

var PosixUstarFormat = {};

var TarStreamEntryHeader = {};

var TarStreamEntry = {};

var UntarStream = {};

export {
  TarStreamFile ,
  TarStreamOptions ,
  TarStreamDir ,
  TarStreamInput ,
  TarStream ,
  OldStyleFormat ,
  PosixUstarFormat ,
  TarStreamEntryHeader ,
  TarStreamEntry ,
  UntarStream ,
}
/* No side effect */
