// Generated by ReScript, PLEASE EDIT WITH CARE


var SchemaType = {};

var $$Error = {};

var ParseOptions = {};

var StylesVariant = {};

var StringifyOptions = {};

export {
  SchemaType ,
  $$Error ,
  ParseOptions ,
  StylesVariant ,
  StringifyOptions ,
}
/* No side effect */
